export const buttons = [
    { digit: 'C', color: 'tertiary', value: 'reset' },
    { digit: '%', color: 'primary', value: 'modulo' },
    { digit: '÷', color: 'primary', value: 'divide' },
    { digit: 7, color: 'secondary', value: 'seven' },
    { digit: 8, color: 'secondary', value: 'eight' },
    { digit: 9, color: 'secondary', value: 'nine' },
    { digit: '*', color: 'primary', value: 'multiply' },
    { digit: 4, color: 'secondary', value: 'four' },
    { digit: 5, color: 'secondary', value: 'five' },
    { digit: 6, color: 'secondary', value: 'six' },
    { digit: 1, color: 'secondary', value: 'one' },
    { digit: '-', color: 'primary', value: 'subtract' },
    { digit: 2, color: 'secondary', value: 'two' },
    { digit: 3, color: 'secondary', value: 'three' },
    { digit: '+', color: 'primary', value: 'add' },
    { digit: 0, color: 'secondary', value: 'zero' },
    { digit: '.', color: 'secondary', value: 'dot' },
    { digit: '=', color: 'primary', value: 'result' },
];
